package py.edu.fiuni.Juegos;

import py.edu.fiuni.addImagenes.FondoPanel;
import py.edu.fiuni.addImagenes.AddImage;
import py.edu.fiuni.nuevosDatosPlay.BasePlay;
import py.edu.fiuni.Juegos.Juegos;
import py.edu.fiuni.nuevosDatosPC.BasePC;
import py.edu.fiuni.nuevosDatosWII.BaseWII;
import py.edu.fiuni.nuevosDatosXBOX.BaseXbox;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Esta clase se encarga de añadir nuevos juegos
 * @author Jorge Martinez
 */
public class JAddJuegos extends javax.swing.JFrame {

    /**
     * Creates new form PanelAddJuegos
     */
    public JAddJuegos() {
        initComponents();
        this.setLocationRelativeTo(null);
        add = new AddImage();
        add.iconoLabel("src/Iconos/Logo.png", jlbLogo);
        play = new BasePlay();
        juego = new Juegos();
        xbox = new BaseXbox();
        wii = new BaseWII();
        pc = new BasePC();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new FondoPanel("/Fondos/FondoPixel.jpg");
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextTitulo = new javax.swing.JTextField();
        jTextDescripcion = new javax.swing.JTextField();
        jTextMonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlbLogo = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTextGenero = new javax.swing.JTextField();
        jCmbTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titulo");

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción");

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto");

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Genero");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setDefaultCapable(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        jCmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un tipo", "Play Station", "XBOX", "WII", "PC" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Consola");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnCancelar)
                                .addGap(50, 50, 50)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(jTextDescripcion)
                                    .addComponent(jTextTitulo)
                                    .addComponent(jLabel2))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Hace invisible el panel
     *
     * @param evt
     */
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarMouseClicked
    /**
     *Este metodo se encarga de guardar los datos que se digitan 
     * @param evt
     */
    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        String titulo = "";
        String descripcion = "";
        String genero = "";
        String monto = "";
        double dinero = 0;
        String mensaje = " ";
        String tipo = " ";

        try {
            titulo = jTextTitulo.getText().toLowerCase();
            descripcion = jTextDescripcion.getText().toLowerCase();
            genero = jTextGenero.getText().toLowerCase();
            monto = jTextMonto.getText();
            dinero = Double.parseDouble(monto);
            tipo = (String) jCmbTipo.getSelectedItem();
            //SI ES QUE NO SE ELIGE NINGUN TIPO DE CONSOLA
            if (tipo.equals("Elige un tipo")) {
                mensaje = "Error";
                JOptionPane.showMessageDialog(null, "➲ Elige un tipo de CONSOLA ☹","",0,add.dimensionarImagen("src/ImagenJuegos/error.png", 70,70));
            }
        } catch (HeadlessException | NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Hubo un error en uno de los datos ingresado\n"
                    + "Compruebelo!\n" + "➤ ➤ Has digitado:\n" + "➥Titulo: " + titulo + "\n" + "➥Descripcion: " + descripcion + "\n" + "➥Genero: " + genero
                    + "\n➥Monto: " + monto,"ERROR ↵ ↵ ",0,add.dimensionarImagen("src/ImagenJuegos/error.png", 100,100));
            mensaje = "Error";
        }
        juego.setTitulo(titulo);
        juego.setDescripcion(descripcion);
        juego.setCategoria(genero);
        juego.setMonto((int) dinero);
        //Metodo
        tipoConsola(tipo, titulo, mensaje);

    }//GEN-LAST:event_btnAgregarMouseClicked
    /**
     * Este metodo dependera del tipo de consola que se le pase para que guarde
     * en la base de datos correspondiente.
     *
     * @param tipo
     * @param titulo
     * @param mensaje
     * @throws HeadlessException
     */
    private void tipoConsola(String tipo, String titulo, String mensaje) throws HeadlessException {
        //EL TIPO DE CONSOLA QUE SE ELIGIO
        switch (tipo) {
            case "Play Station":              
                if (play.existeDentroDeLaBase(titulo) && mensaje != "Error") {
                    play.guardarEnArchivos(juego);
                    JOptionPane.showMessageDialog(null, "➯ Agregado con exito","",0,add.dimensionarImagen("src/ImagenJuegos/agregar.png", 70,70));
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "➯ El juego digitado ya existe dentro de la lista","",0,add.dimensionarImagen("src/ImagenJuegos/error.png", 70,70));
                }
                break;
            case "XBOX":
                if (xbox.existeDentroDeLaBase(titulo) && mensaje != "Error") {
                    xbox.guardarEnArchivos(juego);
                    JOptionPane.showMessageDialog(null, "➯ Agregado con exito","",0,add.dimensionarImagen("src/ImagenJuegos/agregar.png", 70,70));
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "➯ El juego digitado ya existe dentro de la lista","",0,add.dimensionarImagen("src/ImagenJuegos/error.png", 70,70));
                }
                break;
            case "WII":
                if (wii.existeDentroDeLaBase(titulo) && mensaje != "Error") {
                    wii.guardarEnArchivos(juego);
                    JOptionPane.showMessageDialog(null, "➯ Agregado con exito","",0,add.dimensionarImagen("src/ImagenJuegos/agregar.png", 70,70));
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "➯ El juego digitado ya existe dentro de la lista","",0,add.dimensionarImagen("src/ImagenJuegos/error.png", 70,70));
                }
                break;
            case "PC":
                if (pc.existeDentroDeLaBase(titulo) && mensaje != "Error") {
                    pc.guardarEnArchivos(juego);
                    JOptionPane.showMessageDialog(null, "➯ Agregado con exito","",0,add.dimensionarImagen("src/ImagenJuegos/agregar.png", 70,70));
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "➯ El juego digitado ya existe dentro de la lista","",0,add.dimensionarImagen("src/ImagenJuegos/error.png", 70,70));
                }
                break;
            default:

        }
    }
    //Clases necesarias
    private final BaseXbox xbox;
    private final BasePlay play;
    private final BaseWII wii;
    private final BasePC pc;
    private final Juegos juego;
    private final AddImage add;

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jCmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextGenero;
    private javax.swing.JTextField jTextMonto;
    private javax.swing.JTextField jTextTitulo;
    private javax.swing.JLabel jlbLogo;
    // End of variables declaration//GEN-END:variables
}
