/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.categorias;

import py.edu.fiuni.nuevosDatosPlay.GenerosPlay;
import py.edu.fiuni.addImagenes.AddImage;
import py.edu.fiuni.addImagenes.FondoPanel;
import py.edu.fiuni.ventanasPrincipales.JInicio;
import py.edu.fiuni.cliente.ClientesMetodos;
import py.edu.fiuni.generos.DescripcionJuegosPlay;
import py.edu.fiuni.generos.Jjuegos;

/**
 * Ventana que se encarga de mostrar los juegos en pantalla para poder
 * alquilarlos
 *
 * @author Luz Lamas
 */
public class JPlayStation extends javax.swing.JFrame {

    /**
     * Creates new form PlayStation
     */
    public JPlayStation() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1200, 710);
        add.iconoLabel("src/Iconos/logo.png ", logo);
        add.iconoLabel("src/Iconos/pikachu.png ", pikachu);
        add.iconoLabel("src/Iconos/ico1.png", ico1);
        add.iconoLabel("src/Iconos/ico2.png", ico2);
        add.iconoLabel("src/Iconos/ico3.png", ico3);
        add.iconoLabel("src/Iconos/ico4.png", ico4);
        //gif de trailer
        add.iconoLabel("src/trailer/godOfWar.gif", trailer);

        //Button de juegos
        add.addBtnImagen("src/Juegos/kombat.jpg", kombat);
        add.addBtnImagen("src/Juegos/sonic.jpg", sonic);
        add.addBtnImagen("src/Juegos/assassins.jpg", assassings);
        add.addBtnImagen("src/Juegos/destiny.jpg", destiny);
        add.addBtnImagen("src/Juegos/duty.jpg", duty);
        add.addBtnImagen("src/Juegos/fifa16.jpg", fifa16);
        //botones de menu
        inicio.setIcon(add.dimensionarImagen("src/Iconos/inicio.png", 25, 25));
        usuario.setIcon(add.dimensionarImagen("src/Iconos/usuario.png", 25, 25));
        usuario.setText("<html>Usuario<br>CI: " + metodo.ultimoRegitro());
        genero.setIcon(add.dimensionarImagen("src/Iconos/genero.png", 25, 25));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new FondoPanel("/Fondos/fondo.png");
        jLabel1 = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        usuario = new javax.swing.JButton();
        pikachu = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        genero = new javax.swing.JButton();
        jPanel3 = new FondoPanel("/Fondos/fondo3.png");
        kombat = new javax.swing.JButton();
        sonic = new javax.swing.JButton();
        assassings = new javax.swing.JButton();
        destiny = new javax.swing.JButton();
        trailer = new javax.swing.JLabel();
        jPanel1 = new FondoPanel("/Fondos/fondoSuperior.png");
        fifa16 = new javax.swing.JButton();
        duty = new javax.swing.JButton();
        ico1 = new javax.swing.JLabel();
        ico2 = new javax.swing.JLabel();
        ico3 = new javax.swing.JLabel();
        ico4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Menu");

        inicio.setBackground(new java.awt.Color(0, 51, 102));
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("Inicio");
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });

        usuario.setBackground(new java.awt.Color(0, 51, 102));
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario");

        pikachu.setText("jLabel2");

        genero.setBackground(new java.awt.Color(0, 51, 102));
        genero.setForeground(new java.awt.Color(255, 255, 255));
        genero.setText("Genero");
        genero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuario)
                            .addComponent(genero))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(pikachu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inicio)
                .addGap(18, 18, 18)
                .addComponent(usuario)
                .addGap(18, 18, 18)
                .addComponent(genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(pikachu, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        kombat.setText("uno");
        kombat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kombatMouseClicked(evt);
            }
        });

        sonic.setText("dos");
        sonic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sonicMouseClicked(evt);
            }
        });
        sonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonicActionPerformed(evt);
            }
        });

        assassings.setText("tres");
        assassings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assassingsMouseClicked(evt);
            }
        });

        destiny.setText("cuatro");
        destiny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destinyMouseClicked(evt);
            }
        });

        trailer.setBackground(new java.awt.Color(255, 102, 255));
        trailer.setText("gif:v");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 927, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        fifa16.setText("jButton3");
        fifa16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fifa16MouseClicked(evt);
            }
        });

        duty.setText(" ");
        duty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dutyMouseClicked(evt);
            }
        });

        ico1.setText("\n");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mejores Juegos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(trailer, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(kombat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sonic, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(assassings, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destiny, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fifa16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(duty, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ico2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ico3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ico4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(trailer, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kombat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sonic, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assassings, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destiny, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fifa16, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duty, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ico1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ico2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ico3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ico4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonicActionPerformed
    /**
     * boton que se encarga de llamar a la ventana genero para mostrar mas
     * variedades de juegos
     *
     * @param evt
     */
    private void generoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoMouseClicked
        GenerosPlay generos = new GenerosPlay();
        generos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generoMouseClicked
    /**
     * boton que se encarga de volver a la ventana de inicio
     *
     * @param evt
     */
    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        // TODO add your handling code here:
        JInicio sigPanel = new JInicio();
        sigPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inicioMouseClicked
    /**
     * Accion que llama a una clase de alquiler que busca una pequeña descripcion
     * para el juego
     *
     * @param evt
     */
    private void kombatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kombatMouseClicked
        // TODO add your handling code here:
        Jjuegos sigPanel = new Jjuegos("Mortal Kombat", juego.Accion("Mortal Kombat"));
        sigPanel.categoria("PLAY");
        sigPanel.setVisible(true);
    }//GEN-LAST:event_kombatMouseClicked
    /**
     * Accion que llama a una clase de alquiler que busca una pequeña descripcion
     * para el juego
     *
     * @param evt
     */
    private void sonicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonicMouseClicked
        // TODO add your handling code here:
        Jjuegos sigPanel = new Jjuegos("Team Sonic Racing PS4", juego.Carrera("Team Sonic"));
        sigPanel.categoria("PLAY");
        sigPanel.setVisible(true);
    }//GEN-LAST:event_sonicMouseClicked
    /**
     * Accion que llama a una clase de alquiler que busca una pequeña descripcion
     * para el juego
     *
     * @param evt
     */
    private void assassingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assassingsMouseClicked
        // TODO add your handling code here:
        Jjuegos sigPanel = new Jjuegos("Assassin's Creed Odyssey PS4", juego.Aventura("Assassin's"));
        sigPanel.categoria("PLAY");
        sigPanel.setVisible(true);
    }//GEN-LAST:event_assassingsMouseClicked
    /**
     * Accion que llama a una clase de alquiler  que busca una pequeña descripcion
     * para el juego
     *
     * @param evt
     */
    private void destinyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinyMouseClicked
        // TODO add your handling code here:
        Jjuegos sigPanel = new Jjuegos("Destiny", juego.Accion("Destiny"));
        sigPanel.categoria("PLAY");
        sigPanel.setVisible(true);
    }//GEN-LAST:event_destinyMouseClicked
    /**
     * Accion que llama a una clase de alquiler que busca una pequeña descripcion
     * para el juego
     *
     * @param evt
     */
    private void fifa16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fifa16MouseClicked
        // TODO add your handling code here:
        Jjuegos sigPanel = new Jjuegos("Fifa 16", juego.Estrategia("fifa"));
        sigPanel.categoria("PLAY");
        sigPanel.setVisible(true);
    }//GEN-LAST:event_fifa16MouseClicked
    /**
     * Accion que llama a una clase de alquiler que busca una pequeña descripcion
     * para el juego
     *
     * @param evt
     */
    private void dutyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dutyMouseClicked
        // TODO add your handling code here:
        Jjuegos sigPanel = new Jjuegos("Call of Duty: Infinite Warfare", juego.Accion("Call"));
        sigPanel.categoria("PLAY");
        sigPanel.setVisible(true);
    }//GEN-LAST:event_dutyMouseClicked

    private AddImage add = new AddImage();
    private ClientesMetodos metodo = new ClientesMetodos();
    private DescripcionJuegosPlay juego = new DescripcionJuegosPlay();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assassings;
    private javax.swing.JButton destiny;
    private javax.swing.JButton duty;
    private javax.swing.JButton fifa16;
    private javax.swing.JButton genero;
    private javax.swing.JLabel ico1;
    private javax.swing.JLabel ico2;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel ico4;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kombat;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pikachu;
    private javax.swing.JButton sonic;
    private javax.swing.JLabel trailer;
    private javax.swing.JButton usuario;
    // End of variables declaration//GEN-END:variables
}
