/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.nuevosDatosPlay;

import py.edu.fiuni.addImagenes.AddImage;
import py.edu.fiuni.cliente.Cliente;
import py.edu.fiuni.cliente.ClientesMetodos;
import py.edu.fiuni.generos.AlquilerJuegos;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase se encarga de contener al Panel de los Juegos de la Play Station
 *
 * @author Jorge Martinez
 */
public class JPStation extends javax.swing.JFrame {

    private Cliente cliente;
    private ClientesMetodos mdosCliente;

    /**
     * Creates new form JPlayStation
     */
    public JPStation() {
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setUndecorated(true);
        initComponents();

        this.setLocationRelativeTo(null);
        cliente = new Cliente();
        mdosCliente = new ClientesMetodos();
        add.iconoLabel("src/ImagenJuegos/Play.jpg", jLabel1);
        add.iconoLabel("src/Iconos/logo.png", jLabel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlay = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnAlquilar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tablePlay = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablePlay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Descripción", "Categoria", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePlay);
        if (tablePlay.getColumnModel().getColumnCount() > 0) {
            tablePlay.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablePlay.getColumnModel().getColumn(1).setPreferredWidth(350);
            tablePlay.getColumnModel().getColumn(2).setPreferredWidth(25);
            tablePlay.getColumnModel().getColumn(3).setPreferredWidth(25);
        }

        btnActualizar.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 51));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        btnAlquilar.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAlquilar.setForeground(new java.awt.Color(0, 0, 51));
        btnAlquilar.setText("Alquilar");
        btnAlquilar.setBorderPainted(false);
        btnAlquilar.setContentAreaFilled(false);
        btnAlquilar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlquilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlquilarMouseClicked(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAlquilar)
                    .addComponent(btnActualizar))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Este metodo se encarga de pedir el nombre del juego que desea alquilar y
     * pregunta si es que existe ese juego digitado dentro de la base de datos
     *
     * @param evt
     */
    private void btnAlquilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlquilarMouseClicked
        String juego = " ";
        try {
            juego = JOptionPane.showInputDialog("Digite el nombre del juego que desea comprar" + "\n➫ Obs: sea claro con el nombre del juego!").toLowerCase();

        } catch (Exception e) {
            //pequeños errores 
        }
        if (!play.existeDentroDeLaBase(juego)) {
            String monto = play.dameMonto(juego);
            String jugar = juego;
            AlquilerJuegos compra = new AlquilerJuegos(jugar, monto);
            compra.setTitulo(jugar);
            compra.setMonto(monto);
            compra.alquilarJuego(compra);
            cliente.setNombre(mdosCliente.buscarNombre(mdosCliente.ultimoRegitro()));
            cliente.setApellido(mdosCliente.buscarApellido(mdosCliente.ultimoRegitro()));
            cliente.setCedula(mdosCliente.ultimoRegitro());
            cliente.setDireccion(mdosCliente.buscarDomicilio(mdosCliente.ultimoRegitro()));
            mdosCliente.guardarCompra(cliente);
            JOptionPane.showMessageDialog(null, "➫ Procedimiento realizado exitosamente!", "", 0, add.dimensionarImagen("src/Iconos/Aok.png", 70, 70));

        } else if (juego != null && juego != " ") {
            JOptionPane.showMessageDialog(null, "➫ El nombre del juego no fue introducido correctamente", "", 0, add.dimensionarImagen("src/ImagenJuegos/error.png", 70, 70));
        }
    }//GEN-LAST:event_btnAlquilarMouseClicked
    /**
     * Este metodo se encarga de actualizar la jtable con los datos
     * recientemente agregados
     *
     * @param evt
     */
    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked

        tablePlay.setModel(listaJPlay());
        tablePlay.getColumnModel().getColumn(0).setPreferredWidth(70);
        tablePlay.getColumnModel().getColumn(1).setPreferredWidth(350);
        tablePlay.getColumnModel().getColumn(2).setPreferredWidth(25);
        tablePlay.getColumnModel().getColumn(3).setPreferredWidth(25);
    }//GEN-LAST:event_btnActualizarMouseClicked
    /**
     * Hacce invisible la ventana
     *
     * @param evt
     */
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.setVisible(false);

    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * Este metodo se encarga de agregar los datos cargados a un jtable y lo
     * retorna
     *
     * @return
     */
    public DefaultTableModel listaJPlay() {
        String c[] = {"Titulo", "Descripción", "Categoria", "Monto"};
        DefaultTableModel tablet = new DefaultTableModel(c, 0);
        try {
            BufferedReader buffer = new BufferedReader(new FileReader("juegosPlay.txt"));
            String p;
            while ((p = buffer.readLine()) != null) {

                StringTokenizer datos = new StringTokenizer(p, "|");

                Vector vector = new Vector();
                while (datos.hasMoreTokens()) {
                    vector.addElement(datos.nextToken());
                }
                tablet.addRow(vector);

            }
        } catch (IOException ex) {
            System.out.println("Error" + ex.getLocalizedMessage());
        }
        return tablet;
    }

    //Clases necesarias 
    private final AddImage add = new AddImage();
    private final BasePlay play = new BasePlay();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePlay;
    // End of variables declaration//GEN-END:variables
}
