/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.nuevosDatosWII;

import py.edu.fiuni.addImagenes.AddImage;
import py.edu.fiuni.cliente.Cliente;
import py.edu.fiuni.cliente.ClientesMetodos;
import py.edu.fiuni.generos.AlquilerJuegos;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase se encarga de contener al panel de los juegos de WII
 *
 * @author Jorge Martinez
 */
public class JWii extends javax.swing.JFrame {

    private Cliente cliente;
    private ClientesMetodos mdosCliente;

    /**
     * Creates new form JWii
     */
    public JWii() {
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        cliente = new Cliente();
        mdosCliente = new ClientesMetodos();
        add.iconoLabel("src/ImagenJuegos/Wii.jpg", jLabel2);
        add.iconoLabel("src/Iconos/logo.png", jLabel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableWii = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnAlquilar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tableWii.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Descripción", "Categoria", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableWii);
        if (tableWii.getColumnModel().getColumnCount() > 0) {
            tableWii.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableWii.getColumnModel().getColumn(1).setPreferredWidth(350);
            tableWii.getColumnModel().getColumn(2).setPreferredWidth(25);
            tableWii.getColumnModel().getColumn(3).setPreferredWidth(25);
        }

        btnActualizar.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(102, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        btnAlquilar.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAlquilar.setForeground(new java.awt.Color(102, 0, 0));
        btnAlquilar.setText("Alquilar");
        btnAlquilar.setContentAreaFilled(false);
        btnAlquilar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlquilar.setDefaultCapable(false);
        btnAlquilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlquilarMouseClicked(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setDefaultCapable(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlquilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /**
     * Este metodo se encarga de actualizar la jtable con los nuevos datos
     * digitados
     *
     * @param evt
     */
    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        tableWii.setModel(listaJWii());
        tableWii.getColumnModel().getColumn(0).setPreferredWidth(70);
        tableWii.getColumnModel().getColumn(1).setPreferredWidth(350);
        tableWii.getColumnModel().getColumn(2).setPreferredWidth(25);
        tableWii.getColumnModel().getColumn(3).setPreferredWidth(25);
    }//GEN-LAST:event_btnActualizarMouseClicked
    /**
     * Este metodo se encarga de pedir el nombre del juego que desea alquilar y
     * pregunta si es que existe ese juego digitado dentro de la base de datos
     *
     * @param evt
     */
    private void btnAlquilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlquilarMouseClicked
        String juego = " ";
        try {
            juego = JOptionPane.showInputDialog("Digite el nombre del juego que desea comprar" + "\n➫ Obs: sea claro con el nombre del juego!").toLowerCase();

        } catch (Exception e) {
            //pequeños errores
        }
        if (!wii.existeDentroDeLaBase(juego)) {
            String monto = wii.dameMonto(juego);
            String jugar = juego;
            AlquilerJuegos compra = new AlquilerJuegos(jugar, monto);
            compra.setTitulo(jugar);
            compra.setMonto(monto);
            compra.alquilarJuego(compra);
            cliente.setNombre(mdosCliente.buscarNombre(mdosCliente.ultimoRegitro()));
            cliente.setApellido(mdosCliente.buscarApellido(mdosCliente.ultimoRegitro()));
            cliente.setCedula(mdosCliente.ultimoRegitro());
            cliente.setDireccion(mdosCliente.buscarDomicilio(mdosCliente.ultimoRegitro()));
            mdosCliente.guardarCompra(cliente);
            JOptionPane.showMessageDialog(null, "➫ Procedimiento realizado exitosamente!", "", 0, add.dimensionarImagen("src/Iconos/Aok.png", 70, 70));
        } else if (juego != null && juego != " ") {
            JOptionPane.showMessageDialog(null, "➫ El nombre del juego no fue introducido correctamente", "", 0, add.dimensionarImagen("src/ImagenJuegos/error.png", 70, 70));
        }
    }//GEN-LAST:event_btnAlquilarMouseClicked
    /**
     * Hace invisible la ventana
     *
     * @param evt
     */
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * Este metodo retorna una Jtable encargado de agregar los juegos y mostrar
     * en la pantalla
     *
     * @return
     */
    public DefaultTableModel listaJWii() {
        String c[] = {"Titulo", "Descripción", "Categoria", "Monto"};
        DefaultTableModel tablet = new DefaultTableModel(c, 0);
        try {
            BufferedReader buffer = new BufferedReader(new FileReader("juegosWii.txt"));
            String p;
            while ((p = buffer.readLine()) != null) {

                StringTokenizer datos = new StringTokenizer(p, "|");

                Vector vector = new Vector();
                while (datos.hasMoreTokens()) {
                    vector.addElement(datos.nextToken());

                }
                tablet.addRow(vector);

            }
        } catch (IOException ex) {
            System.out.println("Error" + ex.getLocalizedMessage());
        }
        return tablet;
    }

//Clases importantes
    private final BaseWII wii = new BaseWII();
    private final AddImage add = new AddImage();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableWii;
    // End of variables declaration//GEN-END:variables
}
