/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.ventanasPrincipales;

import py.edu.fiuni.administrador.JAlquilerSemana;
import py.edu.fiuni.administrador.JClientes;
import py.edu.fiuni.Juegos.JDevolverJuego;
import py.edu.fiuni.Juegos.JAddJuegos;
import py.edu.fiuni.addImagenes.FondoPanel;
import py.edu.fiuni.addImagenes.AddImage;
import py.edu.fiuni.categorias.JPC;
import py.edu.fiuni.categorias.JXbox;
import py.edu.fiuni.categorias.JSwitch;
import py.edu.fiuni.categorias.JPlayStation;
import java.awt.event.ActionEvent;

/**
 * Esta clase se encarga de iniciar sesion si es que el cliente ya se encuentra
 * registrado
 *
 * @author Jorge Martinez
 */
public class JInicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JInicio() {
        initComponents();
        this.setSize(1200, 710);
        this.setLocationRelativeTo(null);

        //agregamos las imagenes a los botones
        add.addBtnImagen("src/Iconos/instagram.png", btnInsta);
        add.addBtnImagen("src/Iconos/facebook.png", btnFace);
        add.addBtnImagen("src/Iconos/twitter.png", btnTwit);
        add.addBtnImagen("src/Iconos/Play.jpeg", btnPlay);
        add.addBtnImagen("src/Iconos/WII.jpeg", btnWII);
        add.addBtnImagen("src/Iconos/Xbox.jpeg", btnXBOX);
        add.addBtnImagen("src/Iconos/Steam.jpeg", btnPC);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        PanelSur = new FondoPanel("/Fondos/IPanelSur.jpg");
        btnCreadores = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTelCdres = new javax.swing.JButton();
        btnPoliEmpresa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelOeste = new FondoPanel("/Fondos/IPanelOeste.jpg");
        PanelEste = new FondoPanel("/Fondos/IPanelEste.jpg");
        btnFace = new javax.swing.JButton();
        btnInsta = new javax.swing.JButton();
        btnTwit = new javax.swing.JButton();
        PanelCentral = new FondoPanel("/Fondos/IPanelCentral.jpg");
        btnPlay = new javax.swing.JButton();
        btnWII = new javax.swing.JButton();
        btnXBOX = new javax.swing.JButton();
        btnPC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MenuBAR = new javax.swing.JMenuBar();
        MnuArchivos = new javax.swing.JMenu();
        MnuInfo = new javax.swing.JMenuItem();
        MnuDeudas = new javax.swing.JMenuItem();
        MnuMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MnuComu = new javax.swing.JMenu();
        MnuPagWeb = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreadores.setBackground(new java.awt.Color(0, 0, 102));
        btnCreadores.setForeground(new java.awt.Color(255, 255, 255));
        btnCreadores.setText("Creadores");
        btnCreadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreadoresMouseClicked(evt);
            }
        });

        btnConfig.setBackground(new java.awt.Color(0, 0, 102));
        btnConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnConfig.setText("Configuraciones");
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desarrolladores");

        btnTelCdres.setBackground(new java.awt.Color(0, 0, 102));
        btnTelCdres.setForeground(new java.awt.Color(255, 255, 255));
        btnTelCdres.setText("Telefonos");
        btnTelCdres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelCdres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTelCdresMouseClicked(evt);
            }
        });

        btnPoliEmpresa.setBackground(new java.awt.Color(0, 0, 102));
        btnPoliEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnPoliEmpresa.setText("Politicas de las Empresa");
        btnPoliEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPoliEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPoliEmpresaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contactos");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("tel.:256541");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Capybara@gmail.com");

        javax.swing.GroupLayout PanelSurLayout = new javax.swing.GroupLayout(PanelSur);
        PanelSur.setLayout(PanelSurLayout);
        PanelSurLayout.setHorizontalGroup(
            PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSurLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTelCdres)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPoliEmpresa)
                    .addComponent(jLabel2)
                    .addComponent(btnConfig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61))
        );
        PanelSurLayout.setVerticalGroup(
            PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSurLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConfig)
                        .addComponent(btnCreadores))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTelCdres)
                    .addComponent(jLabel5)
                    .addComponent(btnPoliEmpresa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSur, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout PanelOesteLayout = new javax.swing.GroupLayout(PanelOeste);
        PanelOeste.setLayout(PanelOesteLayout);
        PanelOesteLayout.setHorizontalGroup(
            PanelOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelOesteLayout.setVerticalGroup(
            PanelOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );

        getContentPane().add(PanelOeste, java.awt.BorderLayout.LINE_START);

        btnFace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFaceMouseClicked(evt);
            }
        });

        btnInsta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstaMouseClicked(evt);
            }
        });

        btnTwit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTwit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTwitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelEsteLayout = new javax.swing.GroupLayout(PanelEste);
        PanelEste.setLayout(PanelEsteLayout);
        PanelEsteLayout.setHorizontalGroup(
            PanelEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEsteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFace, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTwit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelEsteLayout.setVerticalGroup(
            PanelEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEsteLayout.createSequentialGroup()
                .addGroup(PanelEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFace, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 763, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEste, java.awt.BorderLayout.LINE_END);

        btnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnWII.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWII.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWIIMouseClicked(evt);
            }
        });

        btnXBOX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXBOX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXBOXMouseClicked(evt);
            }
        });

        btnPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPCMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nintendo");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("XBOX");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PC");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PlayStation");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("                      No olvides ir a menu para registrarte y iniciar sesion");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("                                   antes de elegir una de estas categorias");

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                            .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCentralLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(48, 48, 48)
                            .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                                    .addComponent(btnWII, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)
                                    .addComponent(btnXBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(99, 99, 99)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)))
                            .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelCentralLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41))))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCentralLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnWII, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCentralLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPC, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(327, 327, 327))
        );

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        MenuBAR.setForeground(new java.awt.Color(240, 240, 240));

        MnuArchivos.setText("Archivos");
        MnuArchivos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        MnuInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MnuInfo.setText("Informe");
        MnuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuInfoActionPerformed(evt);
            }
        });
        MnuArchivos.add(MnuInfo);

        MnuDeudas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MnuDeudas.setText("Clientes");
        MnuDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuDeudasActionPerformed(evt);
            }
        });
        MnuArchivos.add(MnuDeudas);

        MenuBAR.add(MnuArchivos);

        MnuMenu.setText("Menu");
        MnuMenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenu1.setText("Usuarios");

        jMenuItem2.setText("Iniciar Sesión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Registrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        MnuMenu.add(jMenu1);

        jMenu2.setText("Juegos");

        jMenuItem4.setText("Agregar ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Devolver");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        MnuMenu.add(jMenu2);

        MenuBAR.add(MnuMenu);

        MnuComu.setText("Comunidad");
        MnuComu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        MnuPagWeb.setBackground(new java.awt.Color(0, 153, 153));
        MnuPagWeb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MnuPagWeb.setText("Pagina Web");
        MnuPagWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuPagWebActionPerformed(evt);
            }
        });
        MnuComu.add(MnuPagWeb);

        MenuBAR.add(MnuComu);

        setJMenuBar(MenuBAR);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void MnuDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuDeudasActionPerformed
        JClientes sig = new JClientes();
        sig.setVisible(true);
    }//GEN-LAST:event_MnuDeudasActionPerformed
    /**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        JAddJuegos sigPanel = new JAddJuegos();
        sigPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    /**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
        JPlayStation play = new JPlayStation();

        play.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayMouseClicked
    /**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void btnWIIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWIIMouseClicked
        // TODO add your handling code here: JSwitch swith =new JSwitch();
        JSwitch swith = new JSwitch();
        swith.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWIIMouseClicked
    /**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void btnXBOXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXBOXMouseClicked
        // TODO add your handling code here:

        JXbox xbox = new JXbox();
        xbox.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnXBOXMouseClicked
    /**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void btnPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseClicked
        // TODO add your handling code here:
        JPC pc = new JPC();
        pc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPCMouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        JDevolverJuego sigPanel = new JDevolverJuego();
        sigPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    /**
     * Este metodo te lleva a otro JPanel
     *
     * @param evt
     */
    private void MnuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuInfoActionPerformed
        // TODO add your handling code here:

        JAlquilerSemana sigPanel = new JAlquilerSemana();
        sigPanel.setVisible(true);
    }//GEN-LAST:event_MnuInfoActionPerformed

    /**
     * Este añade diferentes imagenes dentro de un JOption
     *
     * @param evt
     */
    private void btnCreadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreadoresMouseClicked
        accion.addMensajes("Capy✩bara", "src/JOptionPane/Desarrolladores.jpg", 400, 200);
    }//GEN-LAST:event_btnCreadoresMouseClicked
    /**
     * Este añade diferentes imagenes dentro de un JOption
     *
     * @param evt
     */
    private void btnTelCdresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTelCdresMouseClicked
        accion.addMensajes("Capy✩bara", "src/JOptionPane/Contactos.jpg", 400, 200);
    }//GEN-LAST:event_btnTelCdresMouseClicked
    /**
     * Este añade diferentes imagenes dentro de un JOption
     *
     * @param evt
     */
    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        accion.addMensajes("Capy✩bara", "src/JOptionPane/Configuraciones.jpg", 400, 200);
    }//GEN-LAST:event_btnConfigMouseClicked
    /**
     * Este añade diferentes imagenes dentro de un JOption
     *
     * @param evt
     */
    private void btnPoliEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPoliEmpresaMouseClicked
        accion.addMensajes("Capy✩bara", "src/JOptionPane/Politicas.jpg", 450, 220);
    }//GEN-LAST:event_btnPoliEmpresaMouseClicked
    /**
     * Este metodo abre un pagina web
     *
     * @param evt
     */
    private void btnFaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceMouseClicked
        accion.paginasWeb("https://www.facebook.com/");
    }//GEN-LAST:event_btnFaceMouseClicked
    /**
     * Este metodo abre un pagina web
     *
     * @param evt
     */
    private void btnInstaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstaMouseClicked
        accion.paginasWeb("https://www.instagram.com/");
    }//GEN-LAST:event_btnInstaMouseClicked
    /**
     * Este metodo abre un pagina web
     *
     * @param evt
     */
    private void btnTwitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwitMouseClicked
        accion.paginasWeb("https://twitter.com/home");
    }//GEN-LAST:event_btnTwitMouseClicked
    /**
     * Este metodo abre un pagina web
     *
     * @param evt
     */

    private void MnuPagWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuPagWebActionPerformed
        accion.paginasWeb("https://www.britannica.com/animal/capybara");
    }//GEN-LAST:event_MnuPagWebActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JRegisUsuario sigPanel = new JRegisUsuario();
        sigPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed
    /**
     * Este metodo abre un pagina web
     *
     * @param evt
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JIniciarUsser usser = new JIniciarUsser();
        usser.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //Clases
    private AddImage add = new AddImage();
    private final PagRedSocial accion = new PagRedSocial();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBAR;
    private javax.swing.JMenu MnuArchivos;
    private javax.swing.JMenu MnuComu;
    private javax.swing.JMenuItem MnuDeudas;
    private javax.swing.JMenuItem MnuInfo;
    private javax.swing.JMenu MnuMenu;
    private javax.swing.JMenuItem MnuPagWeb;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelEste;
    private javax.swing.JPanel PanelOeste;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnCreadores;
    private javax.swing.JButton btnFace;
    private javax.swing.JButton btnInsta;
    private javax.swing.JButton btnPC;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPoliEmpresa;
    private javax.swing.JButton btnTelCdres;
    private javax.swing.JButton btnTwit;
    private javax.swing.JButton btnWII;
    private javax.swing.JButton btnXBOX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
